trigger:
  - master

pr: none

pool:
  vmImage: windows-2019

resources:
  repositories:
  - repository: templates
    type: git
    name: GitHub.Public/YAML.Templates
    ref: refs/tags/v.1.3.1

steps:
  - template: build.ci.yml@templates
    parameters:
      dotNetSdkVersion: '3.1.x'
      projectName: SimpleConsoleProgress
      unitTestsProjectName: SimpleConsoleProgress.Tests
      sonarCloudProjectKey: filipliwinski_SimpleConsoleProgress
