trigger:
  - master

pr: none

pool:
  vmImage: windows-2019

resources:
  repositories:
  - repository: templates
    type: git
    name: GitHub.Public/YAML.Templates

steps:
  - template: build.ci.yml@templates
    parameters:
      projectName: SimpleConsoleProgress
      unitTestsProjectName: SimpleConsoleProgress.Tests
